import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import styles from "./styles/layout.module.css";
import "./styles/globals.css"
import Header from "./components/ui/Header/Header";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plusJakarta.className}>
        <div className={styles.layoutContainer}>
          <Header />
          <main className={styles.mainContent}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
